<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="105524" started-at="2019-09-07T10:52:34Z" finished-at="2019-09-07T10:54:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="105524" started-at="2019-09-07T10:52:34Z" finished-at="2019-09-07T10:54:19Z">
      <class name="com.crm.testcases.CalenderTest">
        <test-method status="PASS" signature="readCalenderData()[pri:0, instance:com.crm.testcases.CalenderTest@f6c48ac]" name="readCalenderData" is-config="true" duration-ms="102966" started-at="2019-09-07T16:22:34Z" finished-at="2019-09-07T16:24:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readCalenderData -->
        <test-method status="FAIL" signature="newEventTest()[pri:0, instance:com.crm.testcases.CalenderTest@f6c48ac]" name="newEventTest" duration-ms="30" started-at="2019-09-07T16:24:17Z" finished-at="2019-09-07T16:24:17Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.crm.qa.pages.Calender.calenderOpen(Calender.java:46)
	at com.crm.testcases.CalenderTest.newEventTest(CalenderTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- newEventTest -->
        <test-method status="PASS" signature="quit1()[pri:0, instance:com.crm.testcases.CalenderTest@f6c48ac]" name="quit1" is-config="true" duration-ms="2429" started-at="2019-09-07T16:24:17Z" finished-at="2019-09-07T16:24:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit1 -->
      </class> <!-- com.crm.testcases.CalenderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
